name: Update README with Markdown Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract Markdown links and update README
      run: |
        find docs -type f -name "*.md" -exec awk -v RS= '{gsub(/\n/, " "); print "[" FILENAME "](" FILENAME ")"}' {} \; > links.txt
        awk 'BEGIN{p=1} /^## Notes/{print "## Notes"; system("cat links.txt"); p=0} p' README.md > temp_readme.md
        mv temp_readme.md README.md


    - name: Commit and push changes
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "ccbaumler@users.noreply.github.com"
        git add README.md links.txt
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
